name       : pysolfc
version    : 2.0
release    : 1
source     :
    - http://downloads.sourceforge.net/pysolfc/PySolFC-2.0.tar.bz2 : dbcb8e7e6d0479c230745a2be91c0c9b9e8524407cd2075f2dae144e5d441b6c
license    : GPL-3.0
summary    : PySol Fan Club edition
description: |
    PySol Fan Club edition
builddeps  :
setup      : |
build      : |
install    : |
    python setup.py install --root=%installroot% --no-compile -O0
