name       : pysolfc
version    : 2.20.1
release    : 11
source     :
    - https://download.sourceforge.net/project/pysolfc/PySolFC/PySolFC-2.20.1/PySolFC-2.20.1.tar.xz : bb3b90d16810020496e81b9f25fcf563c9fd8704922f24436908874ebca9466a
homepage   : https://pysolfc.sourceforge.io/
license    : GPL-3.0-or-later
component  : games.card
summary    : PySol Fan Club edition
description: |
    PySol Fan Club Edition (PySolFC) is a collection of more than 1000 solitaire card games.
rundeps    :
    - pysolfc-cardsets
    - python-attrs
    - python-configobj
    - python-pillow
    - python-pysol-cards
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
