name       : pysolfc
version    : 2.0
release    : 2
source     :
    - https://superb-dca2.dl.sourceforge.net/project/pysolfc/PySolFC/PySolFC-2.0/PySolFC-2.0.tar.bz2 : dbcb8e7e6d0479c230745a2be91c0c9b9e8524407cd2075f2dae144e5d441b6c
license    : GPL-3.0
component  : games.card
summary    : PySol Fan Club edition
description: |
    PySol Fan Club edition
rundeps  :
    - python-tkinter
install    : |
    %python_install
