name       : pysolfc
version    : 2.18.0
release    : 10
source     :
    - https://download.sourceforge.net/project/pysolfc/PySolFC/PySolFC-2.18.0/PySolFC-2.18.0.tar.xz : d33e01e70b8c56a77d9d300533e80c33007535e8e4c0fc87d782099d9e511089
homepage   : https://pysolfc.sourceforge.io/
license    : GPL-3.0-or-later
component  : games.card
summary    : PySol Fan Club edition
description: |
    PySol Fan Club Edition (PySolFC) is a collection of more than 1000 solitaire card games.
rundeps    :
    - pysolfc-cardsets
    - python-attrs
    - python-configobj
    - python-pillow
    - python-pysol-cards
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
