name       : pysolfc
version    : 2.10.1
release    : 4
source     :
    - https://deac-fra.dl.sourceforge.net/project/pysolfc/PySolFC/PySolFC-2.10.1/PySolFC-2.10.1.tar.xz : f09724f2fdef3f16d8ba5cf834872e31f559bb389f6b5226ff9aa2edbf17d319
homepage   : https://pysolfc.sourceforge.io/
license    : GPL-3.0-or-later
component  : games.card
summary    : PySol Fan Club edition
description: |
    PySol Fan Club Edition (PySolFC) is a collection of more than 1000 solitaire card games.
rundeps    :
    - pysolfc-cardsets
    - python-attrs
    - python-configobj
    - python-pillow
    - python-pysol-cards
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
