name       : pysolfc
version    : 2.14.0
release    : 6
source     :
    - https://deac-fra.dl.sourceforge.net/project/pysolfc/PySolFC/PySolFC-2.14.0/PySolFC-2.14.0.tar.xz : c8463ffddc000494157e7fa7eb7b55615d09c914cf4448d0d882afd1bf1e3da3
homepage   : https://pysolfc.sourceforge.io/
license    : GPL-3.0-or-later
component  : games.card
summary    : PySol Fan Club edition
description: |
    PySol Fan Club Edition (PySolFC) is a collection of more than 1000 solitaire card games.
rundeps    :
    - pysolfc-cardsets
    - python-attrs
    - python-configobj
    - python-pillow
    - python-pysol-cards
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
